"""init6

Revision ID: 0585cc7f4645
Revises: 35641ffdb3c8
Create Date: 2024-05-28 23:10:03.694453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0585cc7f4645'
down_revision: Union[str, None] = '35641ffdb3c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discipline_teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discipline_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group id', sa.Integer(), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.ForeignKeyConstraint(['group id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('discipline', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.drop_constraint('discipline_teacher_id_fkey', 'discipline', type_='foreignkey')
    op.drop_constraint('discipline_group_id_fkey', 'discipline', type_='foreignkey')
    op.create_foreign_key(None, 'discipline', 'subject', ['subject_id'], ['id'])
    op.drop_column('discipline', 'group_id')
    op.drop_column('discipline', 'teacher_id')
    op.drop_column('discipline', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discipline', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('discipline', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('discipline', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'discipline', type_='foreignkey')
    op.create_foreign_key('discipline_group_id_fkey', 'discipline', 'group', ['group_id'], ['id'])
    op.create_foreign_key('discipline_teacher_id_fkey', 'discipline', 'user', ['teacher_id'], ['id'])
    op.drop_column('discipline', 'subject_id')
    op.drop_table('discipline_groups')
    op.drop_table('subject')
    op.drop_table('discipline_teacher')
    # ### end Alembic commands ###
