"""init11

Revision ID: 189ad4bd34f6
Revises: b98b40f56018
Create Date: 2024-05-30 17:49:06.020570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '189ad4bd34f6'
down_revision: Union[str, None] = 'b98b40f56018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discipline_teacher_discipline_id_fkey', 'discipline_teacher', type_='foreignkey')
    op.drop_constraint('discipline_teacher_teacher_id_fkey', 'discipline_teacher', type_='foreignkey')
    op.create_foreign_key(None, 'discipline_teacher', 'discipline', ['discipline_id'], ['id'])
    op.create_foreign_key(None, 'discipline_teacher', 'user', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discipline_teacher', type_='foreignkey')
    op.drop_constraint(None, 'discipline_teacher', type_='foreignkey')
    op.create_foreign_key('discipline_teacher_teacher_id_fkey', 'discipline_teacher', 'group', ['teacher_id'], ['id'])
    op.create_foreign_key('discipline_teacher_discipline_id_fkey', 'discipline_teacher', 'user', ['discipline_id'], ['id'])
    # ### end Alembic commands ###
