"""init12

Revision ID: 4c9173d6011b
Revises: 189ad4bd34f6
Create Date: 2024-05-30 19:45:14.826888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9173d6011b'
down_revision: Union[str, None] = '189ad4bd34f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discipline_subject_id_fkey', 'discipline', type_='foreignkey')
    op.create_foreign_key(None, 'discipline', 'subject', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('discipline_groups_discipline_id_fkey', 'discipline_groups', type_='foreignkey')
    op.drop_constraint('discipline_groups_group_id_fkey', 'discipline_groups', type_='foreignkey')
    op.create_foreign_key(None, 'discipline_groups', 'discipline', ['discipline_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'discipline_groups', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('discipline_teacher_teacher_id_fkey', 'discipline_teacher', type_='foreignkey')
    op.drop_constraint('discipline_teacher_discipline_id_fkey', 'discipline_teacher', type_='foreignkey')
    op.create_foreign_key(None, 'discipline_teacher', 'discipline', ['discipline_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'discipline_teacher', 'user', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('laboratory_discipline_id_fkey', 'laboratory', type_='foreignkey')
    op.create_foreign_key(None, 'laboratory', 'discipline', ['discipline_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('student_laboratory_id_student_fkey', 'student_laboratory', type_='foreignkey')
    op.drop_constraint('student_laboratory_id_lab_fkey', 'student_laboratory', type_='foreignkey')
    op.create_foreign_key(None, 'student_laboratory', 'user', ['id_student'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_laboratory', 'laboratory', ['id_lab'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_group_id_fkey', 'user', type_='foreignkey')
    op.drop_constraint('user_role_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_role_id_fkey', 'user', 'role', ['role_id'], ['id'])
    op.create_foreign_key('user_group_id_fkey', 'user', 'group', ['group_id'], ['id'])
    op.drop_constraint(None, 'student_laboratory', type_='foreignkey')
    op.drop_constraint(None, 'student_laboratory', type_='foreignkey')
    op.create_foreign_key('student_laboratory_id_lab_fkey', 'student_laboratory', 'laboratory', ['id_lab'], ['id'])
    op.create_foreign_key('student_laboratory_id_student_fkey', 'student_laboratory', 'user', ['id_student'], ['id'])
    op.drop_constraint(None, 'laboratory', type_='foreignkey')
    op.create_foreign_key('laboratory_discipline_id_fkey', 'laboratory', 'discipline', ['discipline_id'], ['id'])
    op.drop_constraint(None, 'discipline_teacher', type_='foreignkey')
    op.drop_constraint(None, 'discipline_teacher', type_='foreignkey')
    op.create_foreign_key('discipline_teacher_discipline_id_fkey', 'discipline_teacher', 'discipline', ['discipline_id'], ['id'])
    op.create_foreign_key('discipline_teacher_teacher_id_fkey', 'discipline_teacher', 'user', ['teacher_id'], ['id'])
    op.drop_constraint(None, 'discipline_groups', type_='foreignkey')
    op.drop_constraint(None, 'discipline_groups', type_='foreignkey')
    op.create_foreign_key('discipline_groups_group_id_fkey', 'discipline_groups', 'group', ['group_id'], ['id'])
    op.create_foreign_key('discipline_groups_discipline_id_fkey', 'discipline_groups', 'discipline', ['discipline_id'], ['id'])
    op.drop_constraint(None, 'discipline', type_='foreignkey')
    op.create_foreign_key('discipline_subject_id_fkey', 'discipline', 'subject', ['subject_id'], ['id'])
    # ### end Alembic commands ###
