"""init7

Revision ID: 92ff7205156a
Revises: aecf97cf5f64
Create Date: 2024-06-01 19:55:09.210658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ff7205156a'
down_revision: Union[str, None] = 'aecf97cf5f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discipline', 'info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discipline', sa.Column('info', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
