"""init4

Revision ID: 93ccdd781d2b
Revises: 77e2d104eab5
Create Date: 2024-05-31 22:53:53.757688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ccdd781d2b'
down_revision: Union[str, None] = '77e2d104eab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_laboratory', sa.Column('id_teacher', sa.Integer(), nullable=True))
    op.add_column('student_laboratory', sa.Column('id_discipline', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student_laboratory', 'user', ['id_teacher'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_laboratory', 'discipline', ['id_discipline'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_user_id', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.drop_constraint(None, 'student_laboratory', type_='foreignkey')
    op.drop_constraint(None, 'student_laboratory', type_='foreignkey')
    op.drop_column('student_laboratory', 'id_discipline')
    op.drop_column('student_laboratory', 'id_teacher')
    # ### end Alembic commands ###
