"""init6

Revision ID: aecf97cf5f64
Revises: 24cc72d532db
Create Date: 2024-06-01 14:49:30.362916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aecf97cf5f64'
down_revision: Union[str, None] = '24cc72d532db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_laboratory', sa.Column('valid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_laboratory', 'valid')
    # ### end Alembic commands ###
