"""init8

Revision ID: c36a616e0256
Revises: 524b75c9ecf8
Create Date: 2024-05-29 00:26:24.749353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36a616e0256'
down_revision: Union[str, None] = '524b75c9ecf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_laboratory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_lab', sa.Integer(), nullable=True),
    sa.Column('id_student', sa.Integer(), nullable=True),
    sa.Column('loading_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('count_try', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_lab'], ['laboratory.id'], ),
    sa.ForeignKeyConstraint(['id_student'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_laboratory')
    # ### end Alembic commands ###
