"""init9

Revision ID: e3afc77ef559
Revises: c36a616e0256
Create Date: 2024-05-30 16:32:53.059560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3afc77ef559'
down_revision: Union[str, None] = 'c36a616e0256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discipline_groups', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('discipline_groups_group id_fkey', 'discipline_groups', type_='foreignkey')
    op.create_foreign_key(None, 'discipline_groups', 'group', ['group_id'], ['id'])
    op.drop_column('discipline_groups', 'group id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discipline_groups', sa.Column('group id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'discipline_groups', type_='foreignkey')
    op.create_foreign_key('discipline_groups_group id_fkey', 'discipline_groups', 'group', ['group id'], ['id'])
    op.drop_column('discipline_groups', 'group_id')
    # ### end Alembic commands ###
